baseURL = "https://pensieri-a-margine.netlify.app"
languageCode = "it-it"
title = "Il mio blog"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  ShowReadingTime = true
mainSections = ["posts"]
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

canonifyURLs = true
